/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.juanf.factoryshopclient.gui;

import com.juanf.factoryshared.clases.Producto;
import com.juanf.factoryshopclient.networkClient.TCPClient;
import javax.swing.JOptionPane;

/**
 * Clase Eliminar representa un cuadro de diálogo para eliminar un producto de la bodega.
 * Permite ingresar el ID de un producto y enviarlo al servidor para su eliminación
 * a través de un cliente TCP.
 * 
 * @author Julian Andres
 */
public class Buscar extends javax.swing.JDialog {
    /** Cliente TCP para comunicarse con el servidor. */
    private final TCPClient cliente;
    
    /**
     * Crea una nueva instancia de Eliminar.
     * 
     * @param parent La ventana padre.
     * @param modal Define si el cuadro de diálogo es modal.
     * @param cliente Cliente TCP para enviar datos al servidor.
     */
    public Buscar(java.awt.Frame parent, boolean modal, TCPClient cliente) {
        super(parent, modal);
        this.cliente= cliente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txtnombre = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("buscar articulo de bodega");

        jLabel2.setText("nombre");

        buscar.setText("Buscar Producto");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        salir.setText("X");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel3.setText("id");

        jLabel4.setText("descripcion");

        jLabel5.setText("precio");

        jLabel6.setText("stock");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(salir))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
    /**
     * Método ejecutado cuando se presiona el botón "buscar Producto".
     * Llama al método eliminarProducto para procesar la busqueda del producto.
     * 
     * @param evt Evento de acción.
     */
        buscarProducto();
    }//GEN-LAST:event_buscarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        /**
        * Método ejecutado cuando se presiona el botón "X" para cerrar el cuadro de diálogo.
        *
        * @param evt Evento de acción.
        */
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txtnombre;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

    /**
     * Envía una solicitud al servidor para buscar un producto con el nombre ingresado.
     * Valida que el nombre sea un número entero y muestra mensajes de error en caso de datos inválidos.
     */
    private void buscarProducto() {
        try {
            
            // Obtiene el nombre del producto desde el campo de texto y elimina espacios en blanco.
            String nombre = Txtnombre.getText().trim();
            String respuesta = cliente.sendOperation("SEARCH", new Producto(0, nombre, null, -1, -1));

            // Verifica si la respuesta es nula o indica que el producto no fue encontrado.
            if (respuesta == null || respuesta.equals("NOT_FOUND")) {
                JOptionPane.showMessageDialog(this, "Producto no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            } 
            else {
                JOptionPane.showMessageDialog(this, "Producto encontrado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
                // Separa la respuesta del servidor en atributos usando la coma como delimitador.
                String[] atributos = respuesta.split(",");
                
                // Muestra la información del producto en etiquetas (JLabel).
                jLabel3.setText("ID del producto: "+atributos[0]);  // ID
                jLabel4.setText("Descripcion del producto: "+atributos[1]);  // Descripción
                jLabel5.setText("Precio del producto(unidad)"+atributos[2]);  // Precio
                jLabel6.setText("Cantidad en stock del producto"+atributos[3]);  // Cantidad
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar el producto.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }


}
